### PR TITLE
Resolve #633 by updating to use nodejs v14

### LINKED ISSUE #633: Node.js is outdated in download tools
`civi-download-tools` installs Node.js version 10, which reached EOL in April 2021.

E.g. see [line 502](https://github.com/civicrm/civicrm-buildkit/blob/fee9a80114c10f541a43a57179664fb8dc19fe8b/bin/civi-download-tools#L502)

```
      wget -O- https://deb.nodesource.com/setup_10.x | sudo -E bash -
```

This generates an error message on installation.

I think this should be fixed by updating this to version 14, but wasn't sure if this would cause other issues?

See also [related ticket](https://github.com/michaelmcandrew/civicrm-buildkit-docker/issues/68) for CiviCRM Docker Buildkit.

### PR DESCRIPTION
**Pull request by seamuslee001**
ping @homotechsual @wmortada

### CODE REVIEW

**Comment by wmortada** [comment]
I think this will leave Debian Buster using node.js v10.  I suggest that you add this after line 526:

```
wget -O- https://deb.nodesource.com/setup_14.x | sudo -E bash -
```

**Comment by seamuslee001** [comment]
good point @wmortada added now

**Comment by seamuslee001** [comment]
Mikey is going to test this hopefully in the next day or so

**Comment by homotechsual** [comment]
No issues running this on any supported system. I will however be submitting a PR to remove Disco and adding Hirsute.

**Pull request merged**
