### PR TITLE
add some useful commands

### PR DESCRIPTION
**Pull request by ginkgomzd**
adds these commands

list
the --full option to show
edit

### CODE REVIEW

**Comment by totten** [comment]
Sounds useful.

How would you feel about adding it as a subcommand `civibuild ls` or `civibuild list`:

https://github.com/civicrm/civicrm-buildkit/blob/master/bin/civibuild#L502

To get the path to the build dir, you could use `$BLDDIR` instead of `$(dirname `which civibuild` 2>/dev/null)'/../build'`. This would have the added benefit of working in some custom configurations where BLDDIR has been customized.

**Comment by ginkgomzd** [comment]
adds these commands
 - list
 - the --full option to show
 - edit

**Comment by ginkgomzd** [comment]
@totten This is ready again for your review.
Thanks

**Comment by totten** [comment]
Superceded by #233.

**Pull request closed without merging**
