### PR TITLE
Add in a drupal9-clean build

### PR DESCRIPTION
**Pull request by seamuslee001**
ping @totten @MikeyMJCO

### CODE REVIEW

**Comment by seamuslee001** [comment]
So this has been found to work for me if I apply the following PRs:

https://github.com/civicrm/civicrm-core/pull/17515
https://github.com/civicrm/civicrm-core/pull/17522
https://github.com/civicrm/civicrm-drupal-8/pull/40

And built custom versions of cv with this patch https://github.com/civicrm/cv/pull/75 and drush8 with this patch incorporated https://github.com/drush-ops/drush/pull/4431

**Comment by seamuslee001** [comment]
So the only thing I think that is misssing for our purposes is for there to be a drush8 version that includes that Role PR apart from that this should work correctly on dev-master

**Comment by seamuslee001** [comment]
@MikeyMJCO are you able to test this please?

**Comment by demeritcowboy** [comment]
Tested on WSL. Didn't try anything fancy just checked the site loaded and the civi menus weren't all screwy.

At the beginning drush warned about not being able to find any supported drupal version but then installed 9.0.3 anyway. Otherwise ok.

**Comment by seamuslee001** [comment]
Merging as per @demeritcowboy 's review

**Pull request merged**
