### PR TITLE
prepare civi-download-tools for ubuntu artful

### LINKED ISSUE #398: support ubuntu artful (17.10)
Todo:
- change php7.0* to php7.1*
- change nodejs-legacy to nodejs

### PR DESCRIPTION
**Pull request by DanielvV**
Fixes #398

### CODE REVIEW

**Comment by totten** [comment]
Thanks, @DanielvV.

Just to double-check -- did you test this in a clean environment? Or is it just a first-pass at what ought to work?

**Comment by seamuslee001** [comment]
I remember doing some manual stuff similar to this, I can look to spin up a quick test environment on artful today to confirm it works.

**Comment by seamuslee001** [comment]
@totten i tested this by building an Artful (17.10) VM (desktop version). I then did a git clone and checked out Daniel's branch then ran `./buildkite/bin/civi-download-tools --full` which was successful and was able to do a successful amp config and amp test as well I am a 👍 on merging this

**Comment by totten** [comment]
Thank you, @seamuslee001  and @DanielvV !

**Pull request merged**
