### PR TITLE
Add bee to composer

### PR DESCRIPTION
**Pull request by herbdool**
@totten I figured I'd get the ball rolling of using [bee](https://github.com/backdrop-contrib/bee). Is this also used for the testing architecture?

### CODE REVIEW

**Comment by totten** [comment]
Oh, cool. :)

Yes, the tools defined are used for testing.

---

FWIW, if `bee` had a [PHAR build](https://github.com/backdrop-contrib/bee/issues/197
), that would be a bit easier to incorporate. Compare:

* For the zip file, it needs this download step. But  it also need some kind of stub or symlink in the `bin/` folder. (Symlinks can be done by patching `civi-download-tools`, but that's annoying. A bash or PHP stub might be easier.)
* With a phar file, you can declare it in `phars.json` - then the `bin/` entry will get wired-up at the same time. And you can pin the version.

---

I poked and noticed the related issue at https://github.com/backdrop-contrib/bee/issues/365. So it sounds like the current process is sort-of... "evergreen" or "non-versioned"? (They haven't started doing tags yet?) Obviously, it's great to have version numbers. (Helps with reporting/tracking/analyzing bugs...) But there is an alternative for pinning - use the commit#:

```
https://github.com/OWNER/REPO/archive/COMMIT.zip
https://github.com/backdrop-contrib/bee/archive/82cf3a7cf986fafe0303f0a29af91361dd5c9ada.zip
```

I suspect this would work:

```json
"bee": {
  "version": "82cf3a7cf986fafe0303f0a29af91361dd5c9ada", 
  "_comment": "Updated circa Apr 20, 2024",
  "url": "https://github.com/backdrop-contrib/bee/archive/{$version}.zip", 
  "path": "extern/bee"
},
```

(*Obviously, not quite as pretty for updating.*)

**Comment by herbdool** [comment]
Let's see if we can get a phar and maybe a version then.

**Comment by yorkshire-pudding** [comment]
First release has been added at https://github.com/backdrop-contrib/bee/releases/tag/1.x-1.0.1
Phar is a separate issue https://github.com/backdrop-contrib/bee/issues/197

**Comment by herbdool** [comment]
Now there's a phar as well! Thanks @yorkshire-pudding.

https://github.com/backdrop-contrib/bee/releases/download/1.x-1.0.1/bee.phar

**Comment by herbdool** [comment]
@totten now that there's a phar, I added it to `phars.json`. Not sure what else is required.

**Comment by herbdool** [comment]
bump

**Comment by seamuslee001** [comment]
seems to be an enhancement to me merging

**Pull request merged**
