### PR TITLE
Debian Fixes

### PR DESCRIPTION
**Pull request by MikeyMJCO**
See issue #315 

Issues reported there are fixed in this PR. This PR also tweaks the Debian Stretch installation to remove a duplicate `apt-get update` and print the correct release name.

### CODE REVIEW

**Comment by totten** [comment]
Initially, `civi-download-tools --full` was targetting NodeJS circa v5(or 4? or 6?) because that would make it easier to run the Shoreditch build scripts. A few relevant happenings:

* In `civi-download-tools`, `do_system_stretch()` switched to 8.x circa Sep 2017
* In Shoreditch, the `README.md` was [updated](https://github.com/civicrm/org.civicrm.shoreditch/commit/571d58cbe89d7385013e00a36d1a55b05d10b697#diff-04c6e90faac2675aa89e2176d2eec7d8R14) about two weeks ago recommend 8.x.
* Test infra now tracks `bknix` -- in which the  the all three profiles (`min`/`max`/`dfl`) are currently using NodeJS 6.x.

I'd be interested in determining whether 8.x works with core's protractor and current Shoreditch; if so, we should bump up bknix max as well.

**Comment by MikeyMJCO** [comment]
So I've run and tested with core on 8.x on Stretch and Jessie and on Ubuntu 14.04, 16.04 and 18.04.

**Comment by MikeyMJCO** [comment]
More extensive testing should probably be performed beyond the installation where nodejs is used - however we're already at 8.x for Ubuntu 18.04 and Debian Stretch.

**Comment by MikeyMJCO** [comment]
> I'd be interested in determining whether 8.x **works with core's protractor and current Shoreditch**; if so, we should bump up bknix max as well.


**Protractor:** Works fine.


**Current Shoreditch:** Cloning latest Shoreditch and `npm I` works fine - no errors and builds a working Shoreditch theme.

**Pull request merged**
