### PR TITLE
Deprecate EoL Ubuntu versions.

### PR DESCRIPTION
**Pull request by MikeyMJCO**
This resolves discussion in #432

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
@totten unless you scream I'm gonna merge this - I think @MikeyMJCO made a good case a year ago & it's stronger now

**Comment by MikeyMJCO** [comment]
I can revert the cosmic removal commit.


[MJCO LTD]<https://www.mjco.uk/>
MICHAEL O'TOOLE​
Managing Director
 T
029 2009 7097<tel:029%202009%207097>
 M
07769 901541<tel:07769%20901541>
 E
mikey@mjco.uk<mailto:mikey@mjco.uk>
WWW.MJCO.UK
54 Florentia Street
Cardiff
,
CF24 4PF
[MJCO on Twitter]<https://twitter.com/M_J_C_O>
[MJCO on Facebook]<https://www.facebook.com/mjcouk>
[MJCO on LinkedIn]<https://www.linkedin.com/company/mjco>





We don't expect you to read a page of terms and conditions all we ask is that you let us know if we sent this to the wrong person and we'd like you to know that nothing in this email is intended to form a binding legal contract.
MJCO LTD is a company registered in Wales. Registered Number: 08483853. ​Registered Office: 54 Florentia Street, Cardiff CF24 4PF.

**Comment by eileenmcnaughton** [comment]
That was worth if for the commit 'Revert "Remove Cosmic Cuttlefish"'

**Comment by MikeyMJCO** [comment]
Reverted removal of Cosmic for now. 

I'll re-remove it in a short while - I'm going to add the ability to pass in a parameter to say (for example):

`--full --force-installer=bionic` and in that way - people can force the set of steps closest to their version without us having to have a specific installer for it.

**Comment by eileenmcnaughton** [comment]
I want a bionic installation of me

**Comment by totten** [comment]
"Xenial: Warrior Nerd" lives to install another day.

**Comment by eileenmcnaughton** [comment]
@MikeyMJCO with this merged does buildkit bin/civi-download-tools work for you?

**Comment by MikeyMJCO** [comment]
Testing on fresh Ubu now.

**Comment by MikeyMJCO** [comment]
Yes on 16.04, 18.04, 19.04, no on 14.04

**Pull request merged**
