### PR TITLE
PHPUnit8 Remove warnings attribute from phpunit testsuite to work wi…

### PR DESCRIPTION
**Pull request by seamuslee001**
…th current version of xunit

ping @totten @eileenmcnaughton

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
can you explain this one a bit more?

**Comment by seamuslee001** [comment]
XUnit which is the tool that process the xml results fails if it receives a xml file that doesn't match its standards. PHPUnit8 added warnings metric into the xml output from test runs. the version of XUnit that is currently installed on Jenkins doesn't support the warnings tag see conversation here https://chat.civicrm.org/civicrm/pl/5bzdr7xrqtdjmp54f4fpkqqm5a

**Comment by seamuslee001** [comment]
This removes the warnings metric which makes Xunit be able to process the generated result file

**Comment by eileenmcnaughton** [comment]
@seamuslee001 so the options are upgrade xunit or do this - did you look into the former ?

**Comment by seamuslee001** [comment]
@eileenmcnaughton I did but i'm nervous about doing it as we would need to go from 1.99 to 3.0.2 and it warns "Warning: The new version of this plugin is marked as incompatible with the installed version. This is usually the case because its behavior changed, or because it uses a different settings format than the installed version. Jobs using this plugin may need to be reconfigured, and/or you may not be able to cleanly revert to the prior version without manually restoring old settings. Consult the plugin release notes for details." I don't know what testing regime we have for doing jenkins plugin updates

**Comment by eileenmcnaughton** [comment]
So what are these warnings we are suppressing - it feels like if we suppress them now there is an odds-on chance we will never unsuppress them

**Comment by eileenmcnaughton** [comment]
Also - add the link here https://plugins.jenkins.io/xunit/#documentation -  it looks like version 2 is the one with the breaking changes?

**Comment by seamuslee001** [comment]
@eileenmcnaughton we are suppressing the warnings counter within the junit-xml i.e. we are moving from the top line of each test suites, we are removing the warnings key here

<name="xxx" failures="xxx" passes="xxx" warnings="0">

**Comment by seamuslee001** [comment]
Yes I think its and I didn't just want to go ahead and upgrade the plugin in case it broke our jenkins setup (I have no idea if it will or not)

**Comment by eileenmcnaughton** [comment]
@seamuslee001 OK that warnings counter seems fairly trivial then - I think that by merging this I'm accepting we will never remember to re-enable it but I guess it's ok....

**Pull request merged**
