### PR TITLE
Ensure that CiviGrant extension is enabled on demo sites and appropri…

### PR DESCRIPTION
**Pull request by seamuslee001**
…ate permissions are granted as applicable

@eileenmcnaughton @colemanw

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
Agree with this - as long as it works (ie the extension is enabled before the permissions are added)

D7 = missing ?

My main 'wait for a bit' is just that I think we should sort out the existing permission inconsistencies first (since I hit some on the demo site in testing)

**Comment by seamuslee001** [comment]
@eileenmcnaughton D7 is already granting the permissions necessary https://github.com/civicrm/civicrm-buildkit/blob/master/app/config/drupal-demo/install.sh#L122 however this is only done on the -demo build, PR tests spin up a drupal-clean build not drupal-demo same in wp-demo already https://github.com/civicrm/civicrm-buildkit/blob/master/app/config/wp-demo/install.sh#L120

**Comment by eileenmcnaughton** [comment]
@seamuslee001 hmm - that's a pain - it makes it hard to test the pr site

**Comment by seamuslee001** [comment]
@eileenmcnaughton I note that dmaster has been failing to build because of this https://test.civicrm.org/view/Sites/job/demo.civicrm.org/BLDNAME=dmaster,label=www-demo/2880/console any objections to me merging?

**Pull request merged**
