### PR TITLE
Change Edge PHP version to 8.3 and change max and dfl to be 8.2

### PR DESCRIPTION
**Pull request by seamuslee001**
@totten @eileenmcnaughton

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
thanks @seamuslee001

**Comment by totten** [comment]
This is gonna be interesting to see what happens to the matrices...

**Comment by totten** [comment]
Well... https://test.civicrm.org/job/CiviCRM-Core-Matrix/ ... the effect is not great... and not terrible...

As you'd probably expect, the effect on `5.72` and `master` is fairly small -- adding 2-3 failures within `phpunit-crm,max`. Seems OK since we have some time before release.

For `5.69`, it's throwing 68 failures on `phpunit-crm,max` and 4 on `phpunit-api3`. 70 is  enough to be a challenge to reliably reading the data. I guess we don't actually care about this matrix for 5.69 -- what matters is `Security-Core-Matrix` for `5.69`. (But that's gonna behave the same.) 

For `5.71`, it's throwing 6. Probably small enough that we could potentially forward port fixes.

**Comment by colemanw** [comment]
This is great. I need to use php 8.2 locally (because developing Civix, `box` refuses to run on anything less).
However, after pulling this down, running `civi-download-tools` and restarting my computer a few times, I still am stuck with php 8.1.
I see this:
```bash
> use-bknix dfl -s
> php -v
PHP 8.1.19 (cli)
```
and it seems to be coming from a local profile:
```bash
> which php
/nix/var/nix/profiles/per-user/colemanwatts/bknix-dfl/bin/php
```
I don't remember ever creating a local profile and telling it to lock me on an old version of php, so I just tried deleting that directory:
```bash
> rm -R /nix/var/nix/profiles/per-user/colemanwatts/bknix-dfl
> use-bknix dfl -s
The specified profile does not correspond to an actual profile
```
Oops. Looks like I broke it.

**Comment by colemanw** [comment]
Ok thanks for your help @totten. For future reference the fix required running these 2 commands
```sh
> ./nix/bin/install-developer.sh
> loco clean
```

**Pull request merged**
