### PR TITLE
Multiple fixes for Windows

### PR DESCRIPTION
**Pull request by totten**
Developed with Windows 7 Professional, XAMPP, and Git Bash.

### CODE REVIEW

**Comment by kcristiano** [comment]
I gave this a try.   Used totten/civicrm-buildkit and master-win branch

Windows 7, Git 

I get an error after wp install and it leaves CiviCRM in an unusable state:
```symfony/dependency-injection suggests installing symfony/config ()
symfony/dependency-injection suggests installing symfony/proxy-manager-bridge (Generate service proxies to lazy load them)
symfony/dependency-injection suggests installing symfony/yaml ()
symfony/event-dispatcher suggests installing symfony/http-kernel ()
Generating autoload files
+ has_commands bower karma
+ for cmd in '"$@"'
+ which bower
+ for cmd in '"$@"'
+ which karma
+ return 0
+ npm install --production

> civicrm@4.6.0 postinstall c:\data\projects\buildkit\build\wpcv47.dev\wp-content\plugins\civicrm\civicrm
> bash tools/scripts/npm/postinstall.sh

++ pickcmd node_modules/bower/bin/bower bower
++ for name in '"$@"'
++ which node_modules/bower/bin/bower
++ for name in '"$@"'
++ which bower
++ echo bower
++ return
+ BOWER=bower
+ '[' -f bower ']'
+ '[' -n '' ']'
+ '[' '!' -f bower_components/.setupsh.ts ']'
+ BOWER_OPT=-f
+ '[' -f bower_components/.setupsh.ts ']'
+ bower install -f
module.js:338
    throw err;
          ^
Error: Cannot find module 'q'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (c:\data\projects\buildkit\bin\bower:6:9)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
```
Am I missing a dependency?

**Comment by totten** [comment]
@kcristiano, the only dependency I can really think of here is NodeJS. FWIW:

 * I'm running NodeJS v0.12.2.
 * The "q" dependency is not one that we explicitly include. It's included transitively as part of ```bower``` and ```karma```. On my system, it shows up at these locations:
    * /c/Users/admin/buildkit/node_modules/bower/node_modules/p-throttler/node_modules/q
    * /c/Users/admin/buildkit/node_modules/bower/node_modules/q
    * /c/Users/admin/buildkit/node_modules/karma/node_modules/q
 * Based on that log, it appears to be crashing during the ```setup.sh -D``` step. This step works for me on both ```drupal-demo``` and ```wp-demo```. (However, I'm getting a different error with ```wp-demo```. PHP-CLI seems to timeout while running ```wp rewrite structure /%postname%/```.)
 * Is there a chance that you previously installed ```bower``` for other reasons? Maybe it's mixing up the copies of bower?

**Comment by totten** [comment]
This page suggests something funny in Node/NPM setup: https://github.com/johnpapa/pluralsight-gulp/issues/7

**Comment by kcristiano** [comment]
Thanks for the feedback.   I may have installed bower on that machine.   I'll clean up and try again :)

**Comment by kcristiano** [comment]
@totten The error for me was related to ruby.  Once I removed ruby 2.1 and re-ran civi-download-tools I was fine.  Sort of.

I get an error on `wp rewrite structure /%postname%/`   I commented that out of install.sh and all is well.   This may be my environment, but as this was more an exersize to see if it can work (as I use linux and mac 95+% of the time) I can use it as is.

**Comment by totten** [comment]
Closing due to merge conflict and lack of activity.

I've cherry-picked a few of the safer commits but notably omitted c8c9206 which could be picked up later if someone else wants to work on Windows.

**Pull request closed without merging**
