### PR TITLE
(Don't merge yet) Allow to checkout repos by bransh or tag

### PR DESCRIPTION
**Pull request by omarabuhussein**
Its really useful sometimes to create a new civicrm build via the buildkit using a specific tag instead of branch , This PR add a new option called **checkout** which allow you to specify how the repositories going to be checked out either by tag or branch name .

Examples :

create civicrm drupal demo instance using civicrm 4.7.7 release
```
civibuild d4777 --type drupal-demo --civi-ver 4.7.7 --checkout tag -url http://localhost:8135
```

create civicrm drupal demo instance using latest master branch
```
civibuild dmaster --type drupal-demo --civi-ver master --checkout branch -url http://localhost:8135
```

create civicrm drupal demo instance using 4.7 branch
```
civibuild d47 --type drupal-demo --civi-ver 4.7 --checkout branch -url http://localhost:8135
```

This option for now work for the following build types :

- drupal-demo
- hr15
- hr16

### CODE REVIEW

**Comment by omarabuhussein** [comment]
@totten @AkA84 

What do you think about this ?

**Comment by AkA84** [comment]
@omarabuhussein to me it looks great, it makes the tool more flexible. Only thing would be to make sure the `--checkout` param can be only `branch` or `tag`, without accepting some other value

**Comment by totten** [comment]
@omarabuhussein, I went along with similar (but narrower/less flexible) patch when it only affected HR builds... but don't really understand the use-case where `drush.make` needs to differentiate between a branch or a tag. For example, the current file `app/config/drupal-clean/drush.make.tmpl` uses `branch`:

```
libraries[civicrm][download][branch] = %%CIVI_VERSION%%
```

But it still lets me use tags for CIVI_VERSION:

```
$ civibuild create delme --type drupal-clean --civi-ver 4.7.5
$ cd delme/sites/all/modules/civicrm
$ git status
HEAD detached at 4.7.5
nothing to commit, working directory clean
```

What's the problem being solved by changing this `tag`?

(In case it's relevant, my local system is OSX 10.10 running git version 2.6.4.)

**Comment by omarabuhussein** [comment]
well... I wasn't aware that keeping it like this :
`libraries[civicrm][download][branch] = %%CIVI_VERSION%%`
will accept tag names too and not branches only. But knowing this I now wonder if this PR https://github.com/civicrm/civicrm-buildkit/pull/249  was even necessary .

**Pull request closed without merging**
