### PR TITLE
update debian to support buster, drop jessie

### PR DESCRIPTION
**Pull request by jmcclelland**
https://github.com/civicrm/civicrm-buildkit/issues/462

### CODE REVIEW

**Comment by MikeyMJCO** [comment]
Related: #432

**Comment by jmcclelland** [comment]
Thanks for the feedback. I've updated the patch to preserve jessie while still adding buster.

**Comment by MikeyMJCO** [comment]
Looks good to me - I'm spinning up a Buster VM now to test.

**Comment by MikeyMJCO** [comment]
This is tested and working @totten should be good to merge on this.

**Comment by totten** [comment]
Nice, @jmcclelland @MikeyMJCO ! Merging.

**Pull request merged**
