### PR TITLE
Update transifex

### PR DESCRIPTION
**Pull request by totten**
For #763

### CODE REVIEW

**Comment by totten** [comment]
There's a confusing thing in here:

```
$ nix-shell -A min
[nix-shell:~/bknix]$ which tx 

[nix-shell:~/bknix]$ which cli
/nix/store/hd10f50d7m8fc0bfx813q10yzzr2q719-transifex-cli-1.6.5/bin/cli
```

So it's generating a command named `cli` (which, in fairness, matches the Github project - but it's a bit nondescript). 

It probably needs some kind of extra step. Maybe an `installPhase` step to copy "cli" to "tx"? Or maybe there's an example somewhere in nixpkgs for telling `buildGoModule` to rename the binary?

**Comment by totten** [comment]
Fixing the command-name basically requires adding an extra build step (e.g. `mv bin/cli bin/tx`). Unfortunately, I don't do this enough to _know_ where to put that. But... I was able to find the [implementation of buildGoModule](https://github.com/NixOS/nixpkgs/blob/master/pkgs/build-support/go/module.nix), spot a few key words (`$GOPATH`, `runHook`, `postBuild`), and make a lucky guess:

```
  postBuild = ''
    mv $GOPATH/bin/cli $GOPATH/bin/tx
  '';
```

Which seems to work.

But, dang, I really wish the docs described the parameters for these functions like `buildGoModule`.

**Comment by mlutfy** [comment]
Wow thanks for helping with this, definitely obscure. There is a warning, but it seems to work.

I ran it on my local env, and initially had this non-fatal warning:

```
0 bgm@home:~/repositories/civicrm-buildkit((HEAD detached at totten/master-tx-165))$ nix-shell -A min 
error: file 'nixpkgs' was not found in the Nix search path (add it using $NIX_PATH or -I)

       at «string»:1:9:

            1| (import <nixpkgs> {}).bashInteractive
             |         ^
will use bash from your environment
these 3 derivations will be built:
  /nix/store/bd7976f49wq6397bwbivws71316ibl91-source.drv
  /nix/store/z3says2pi5x13c0mq0ixhzl4a1x52kkm-transifex-cli-1.6.5-go-modules.drv
  /nix/store/2zfwkhr4vigykgca6bqkrmkj490v72xz-transifex-cli-1.6.5.drv
this path will be fetched (96.73 MiB download, 428.78 MiB unpacked):
  /nix/store/jsarcxgrisc7w5znkja44lqqy4zv8cs5-go-1.17.10
copying path '/nix/store/jsarcxgrisc7w5znkja44lqqy4zv8cs5-go-1.17.10' from 'https://cache.nixos.org'...
```

and when it was done, it seemed to work OK:

```
[nix-shell:~/repositories/civicrm-buildkit]$ which tx 
/nix/store/a7dki11238px2sw17wjy6xdx0c939fk9-transifex-cli-1.6.5/bin/tx

[nix-shell:~/repositories/civicrm-buildkit]$ tx 
NAME:
   tx - A new cli application
[...]
```

The command line options seem to be the same as before, so I would be tempted to merge and to run it. It's a bit difficult to test the full process locally.

**Comment by totten** [comment]
> The command line options seem to be the same as before, so I would be tempted to merge and to run it. It's a bit difficult to test the full process locally.

Agree, let's just merge. It sounds like the old client doesn't work anyway, so we might as well try it.

**Pull request merged**
