### PR TITLE
Add environment variable for customizing the "app/config" types

### PR DESCRIPTION
**Pull request by jaapjansma**
With this PR it is possible to declare a configuration option `EXTRA_SITE_CONFIG_DIR` this directory could contain custom site types (without overriding existing ones).

### CODE REVIEW

**Comment by jaapjansma** [comment]
Ah I see now the PR #391 from @michaelmcandrew which is similair

**Comment by totten** [comment]
@jaapjansma Oh, nice! I think this approach is an improvement over #391:

* You don't have type `--type <foo>` frequently. The customization is persistent (`civibuild.conf`).
* But if you want to make the customization momentarily (akin to passing `--type`), you can just pass the env-var at runtime
    ```
    env EXTRA_SITE_CONFIG_DIR=...foo... civibuild create mybuild`
    ```
* If you want the change to be persistent across all builds, then you can put it in `civibuild.conf`.

I tested it out locally, and it worked. 😃 

A few nitpicks about the variable name:

* `EXTRA_SITE_CONFIG_DIR` looks to be named after `SITE_CONFIG_DIR` (which is closely related). But `EXTRA_` implies a sort of interchangeable content; in reality, the content has a different grain. (`SITE_CONFIG_DIR` is *a child path` which contains *the specific configuration used by a given site*. `EXTRA_SITE_CONFIG_DIR` is a place to run search.)
* In Unix variable naming, if you're setting a place to search, it's usually named `xxxPATH` (e.g. `PATH`, `MANPATH`, `LD_LIBRARY_PATH`, `CPATH`, `CLASSPATH`).

I pushed up a change to rename it to `CIVIBUILD_PATH`. If that looks good to you, then I'd say let's merge.

(*Will wait a couple days before merging in case there's feedback.*)

**Comment by jaapjansma** [comment]
I am happy with your improvement.

**Comment by totten** [comment]
Cool. Proposed update for dev docs: https://github.com/civicrm/civicrm-dev-docs/pull/666

**Pull request merged**
