### PR TITLE
[do-not-merge] PCHR-1247: Added Leave and Absences Feature module to enable using drush cmd.

### PR DESCRIPTION
**Pull request by hitesh-jain**
Why this should not be merged ? 
We are waiting for one of the CiviHR branch to be passed to staging , so once la-milestone-3 branch makes it way to staging this should be merged once CiviHR 1.7 is released.

Added Leave and Absences feature module to be enabled automatically whenever a new CiviHR site build happens using drush feature enablement.

### CODE REVIEW

**Comment by AkA84** [comment]
approved

**Comment by totten** [comment]
Question/confusion -- the last comment was "approved" (@AkaA84), but then the title was changed to have prefix `[do-not-merge]`. And then merge-conflict arose. 

So has this been handled by some other means? Inclined to close it.

**Comment by AkA84** [comment]
@totten sorry for the confusion, this is for CiviHR 1.7 which will contain the new Leave and Absence extension (and drupal module+features as well). Given that 1.7 is still currently in development, we don't want this to be merged yet. I don't know if it's a problem to keep it open, if it is then please close it and we'll reopen it when we know we can merge it

**Comment by davialexandre** [comment]
@totten can you please close this? We don't need it anymore. This will be part of a new build type, which will be added by a new PR to be submitted soon.

**Pull request closed without merging**
