### PR TITLE
Remove composer log hack now that composer depdancy has been fixed up…

### PR DESCRIPTION
**Pull request by seamuslee001**
…stream

Now that https://github.com/civicrm/civicrm-core/pull/17460 has been merged we can reduce the composer hacks around pear log for master

### CODE REVIEW

**Comment by totten** [comment]
I tried this:

```
civibuild create d8rec-clean
```

and it ended with:

```

+++ local CIVI_VERSION_COMP=dev-master
+++ EXTRA_COMPOSER=()
+++ local EXTRA_COMPOSER
+++ EXTRA_PATCH=()
+++ local EXTRA_PATCH
+++ case "$CIVI_VERSION" in
+++ echo 'No extra patches required'
No extra patches required
+++ composer require 'civicrm/civicrm-asset-plugin:~1.0.0' civicrm/civicrm-core:dev-master civicrm/civicrm-packages:dev-master civicrm/civicrm-drupal-8:dev-master --prefer-source
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Can only install one of: pear/pear_exception[v1.0.1, v1.0.0].
    - Can only install one of: pear/pear_exception[v1.0.1, v1.0.0].
    - Can only install one of: pear/pear_exception[v1.0.1, v1.0.0].
    - pear/log 1.13.2 requires pear/pear_exception 1.0.1 -> satisfiable by pear/pear_exception[v1.0.1].
    - civicrm/civicrm-core dev-master requires pear/log 1.13.2 -> satisfiable by pear/log[1.13.2].
    - Installation request for civicrm/civicrm-core dev-master -> satisfiable by civicrm/civicrm-core[dev-master].
    - Installation request for pear/pear_exception (locked at v1.0.0) -> satisfiable by pear/pear_exception[v1.0.0].

Installation failed, reverting ./composer.json to its original content.
```


Perhaps because https://github.com/civicrm/civicrm-core/commit/6086c345a00f81bae8735dc78d682cdd96187f19 is still being too precise? 

Haven't really debugged though

**Comment by MikeyMJCO** [comment]
Debugging.

**Comment by MikeyMJCO** [comment]
It works fine for me using the following commands:

1. `composer create-project drupal/recommended-project:'~8.8' d8civi`
1. `composer require 'civicrm/civicrm-asset-plugin:~1.0.0' civicrm/civicrm-core:dev-master civicrm/civicrm-packages:dev-master civicrm/civicrm-drupal-8:dev-master --prefer-source`

**Comment by MikeyMJCO** [comment]
**More testing:**

I've just done the following:

1. Apply this PR/patch to `civibuild.lib.sh`.
1. Run `civibuild create d8rec-clean` 

 I get a failed build. Turns out my command above builds with Drupal 8.9.0 which has bumped it's `pear/pear_exception` dependency. This is going to be an issue for Drupal 8.8.* with the core-recommended package which `"pear/pear_exception": "v1.0.0",`

Basically we need to maintain this fix for Drupal 8.8.* and drop it for `8.9.*` and `9.*.*` where it's not needed (and may cause issues if Drupal is relying on changes to `pear/pear_exception`.

**Comment by MikeyMJCO** [comment]
This is a downside of the Drupal's `core-recommended` package which builds to very specific versions only.

**Pull request closed without merging**
